import streamlit as st

st.title ('TANGKAP')
st.subheader('| About Us')
"""
Merupakan hasil applikasi berbasiskan model machine learning menggunakan Python dan Stream lit yang dapat menjadi solusi untuk membantu perusahaan asuransi dalam mendeteksi kecurangan klaim asuransi.

"""
st.markdown('---')
st.markdown('# Asuransi')
st.markdown('## Apa Itu Asuransi?')
st.write ('Asuransi merupakan perjanjian antara perusahaan asuransi (penanggung) dan pemegang polis (tertanggung) dimana tertanggung membayar sejumlah premi untuk mendapatkan pertanggungan atas risiko kerusakan, tanggung jawab hukum kepada pihak ketiga yang mungkin diderita oleh tertanggung, menerima pembayaran yang didasarkan pada meninggal atau hidupnya tertanggung dengan manfaat yang besarnya telah ditetapkan dan/ atau didasarkan pada hasil pengelolaan dana.')
st.image ('images\klasifikasi _asuransi.png', caption=None, width=None, use_column_width=None, clamp=False, channels="RGB", output_format="auto")
st.markdown('## Apa Itu Perusahaan Asuransi?')
st.write ('Perusahaan asuransi merupakan perusahaan yang bergerak di bidang:')
st.write ('a. Penyediaan jasa pertanggungan atau pengelolaan risiko.')
st.write ('b. Pemasaran dan distribusi produk asuransi(konvensional dan syariah).')
st.markdown('## Apa Itu Perusahaan Asuransi Umum?')
st.write('Asuransi Umum : perusahaan yang memberikan jasa pertanggungan risiko dan penggantian akibat kerugian atau kerusakan atas harta berharga yang dimiliki seperti rumah, toko, gudang, kendaraan bermotor, lahan pertanian, barang dagangan, dan berbagai harta lainnya.')
st.markdown('## Apa Itu Premi?')
st.write ('Uang yang ditetapkan oleh perusahaan asuransi/ reasuransi untuk dibayarkan berdasarkan perjanjian asuransi/ reasuransi atau berdasarkan undang-undang, untuk memperoleh manfaat asuransi.')

st.markdown('---')
st.markdown('# Implementasi Algoritma Machine Learning')
st.markdown('## Apa Itu Machine Learning')
st.write('Machine Learning adalah ilmu yang mempelajari tentang algoritma komputer yang bisa mengenali pola-pola di dalam data, dengan tujuan untuk mengubah beragam macam data menjadi suatu tindakan yang nyata dengan sesedikit mungkin campur tangan manusia.')
st.image ('images\pict1.jpg', caption=None, width=None, use_column_width=None, clamp=False, channels="RGB", output_format="auto")
st.markdown('### Apa Itu Clasifier Supervised Learning')
st.write('Clasifier Supervised Learning umumnya digunakan untuk menemukan pola dalam data masukan yang diberi label sehingga memungkinkan kita menghasilkan data keluaran hasil klasifikasi data kategorik yang benar secara efektif.')
st.image ('images\pict2.png', caption=None, width=None, use_column_width=None, clamp=False, channels="RGB", output_format="auto")
st.markdown('### Apa Itu KNN')
st.write('Algoritma k-NN (k-Nearest Neighbor) merupakan algoritma berbasis supervised learning yang bekerja untuk mencari jarak terdekat dari objek data. Algoritma ini mengasumsikan bahwa tiap instance dari data adalah bertetangga dan instance yang berdekatan dianggap memiliki kelas yang sama. Tujuan dari algoritma ini adalah untuk mengklasifikasikan objek data baru berdasarkan atribut dan sampel dari data latih (training). Algoritma k-NN menggunakan neighborhood classification sebagain nilai prediksi dan nilai instance yang baru. K-Nearest Neighbor Instance Based Learning')
st.markdown('### Apa Itu Decision Tree')
st.write('Konsep Decision Tree adalah mengubah data menjadi pohon keputusan (tree) dan aturan-aturan keputusan (rule).')

st.markdown('### Apa Itu Logistic Regression')
st.write('Logistic Regression merupakan sebuah algoritma yang digunakan untuk melakukan prediksi apakah sesuai bernilai benar atau salah (0 atau 1). Jika pada Linear Regression garis yang terbentuk adalah garis lurus, pada Logistic Regression garis yang terbentuk mirip seperti huruf “S” antara titik 0 sampai 1.')

st.markdown('### Apa Itu Suport Vector Machine (SVM)')
st.write('Support Vector Machine (SVM) merupakan salah satu metode dalam supervised learning yang biasanya digunakan untuk klasifikasi (seperti Support Vector Classification) dan regresi (Support Vector Regression). SVM didasarkan pada gagasan untuk menemukan hyperplane yang memisahkan fitur-fitur menjadi domain yang berbeda.')

st.markdown('### Apa Itu XGBoost')
st.write('XGBoost adalah singkatan dari Extreme Gradient Boosting, yaitu sebuah pustaka machine learning yang dapat melakukan boosting pohon keputusan (decision tree) secara paralel dan terdistribusi. XGBoost merupakan pustaka machine learning yang sangat populer dan efektif untuk menyelesaikan masalah regresi, klasifikasi, dan ranking.')
st.markdown('---')
st.markdown('## Developing Stages')
st.write('Berikut merupakan tahapan pembuatan project TANGKAP')
st.image ('images\pict6.png', caption=None, width=None, use_column_width=None, clamp=False, channels="RGB", output_format="auto")
st.markdown('### Business Understanding')
st.markdown('#### Berikut merupakan Business Understanding dari TANGKAP')
st.write('Asuransi memiliki peran yang penting dalam mengelola risiko kerugian dalam perencaan keuangan. Asuransi umum merupakan perusahaan asuransi yang memberikan layanan jaminan atas asset yang dimiliki baik perusahaan maupun individu. Industri Asuransi Umum di Indonesia memiliki trend pertumbuhan yang baik setiap tahunnya. Besarnya Kompoisi Asuransi umum didominasi oleh asuransi property, dan kendaraan bermotor. Asuransi kendaraan bermotor memiliki Nilai dan Volume klaim yang cukup mempengaruhi laba perusahaan asuransi. Volume klaim kendaraan motor yang tinggi, juga disertai dengan  jumlah Fraud yang terjadi. Oleh karena itu diperlukan tools yang mampu membantu analisa proses klaim tersebut khususnya dalam mendeteksi indikasi fraud.')
st.markdown('#### Berikut merupakan Tujuan dari TANGKAP')
st.write("1. Untuk mengidentifikasi fraud klaim asuransi kendaraan bermotor secara dini sehingga membantu petugas klaim dalam melakukan analisa klaim.")
st.write('2. Sebagai syarat kelulusan peserta didik dalam menyelesaikan study fast track machine learning di green academy.')
st.markdown('#### Berikut merupakan Manfaat dari TANGKAP')
st.write("1. Mendeteksi potensi terjadinya fraud dalam klaim asuransi kendaraan bermotor.")
st.write("2. Meningkatkan awareness dari petugas saat melakukan analisa klaim asuransi kendaraan bermotor.")
st.write("3. Menurunkan nilai klaim dan meningkatkan profit perusahaan asuransi.")
st.write("4. Mewujudkan industry asuransi yang sehat dan terhindar dari pihak-pihak yang mencari keuntungan secara tidak sah.")
st.markdown('### Data Understanding dan Preprocessing')
st.markdown('###### https://data.mendeley.com/datasets/992mh7dk9y/2')
st.markdown('#### Berikut merupakan dataset untuk project TANGKAP')
st.image ('images\pict8.png', caption=None, width=None, use_column_width=None, clamp=False, channels="RGB", output_format="auto")
st.markdown('#### Berikut merupakan data understanding dari dataset untuk project TANGKAP')
st.image ('images\pict9.png', caption=None, width=None, use_column_width=None, clamp=False, channels="RGB", output_format="auto")
st.markdown('#### Berikut merupakan tahapan dari preprocessing untuk project TANGKAP')
st.image ('images\pict7.png', caption=None, width=None, use_column_width=None, clamp=False, channels="RGB", output_format="auto")